# Generated by Django 4.0 on 2022-01-04 14:17

import birth.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='full_name')),
                ('occupation', models.CharField(max_length=120, verbose_name='occupation')),
                ('marital_status', models.CharField(max_length=20, verbose_name='email')),
                ('nni', models.CharField(default=birth.utils.create_new_ref_number, editable=False, max_length=10, unique='True', verbose_name='nni')),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='full_name')),
                ('occupation', models.CharField(max_length=120, verbose_name='occupation')),
                ('marital_status', models.CharField(max_length=20, verbose_name='email')),
                ('nni', models.CharField(default=birth.utils.create_new_ref_number, editable=False, max_length=10, unique='True', verbose_name='nni')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='full_name')),
                ('last_name', models.CharField(max_length=120, verbose_name='full_name')),
                ('birth_time', models.TimeField(verbose_name='birth_time')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('birth_place', models.CharField(max_length=120, verbose_name='birth_place')),
                ('gender', models.CharField(max_length=120, verbose_name='gender')),
                ('nni', models.CharField(default=birth.utils.create_new_ref_number, editable=False, max_length=10, unique='True', verbose_name='nni')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.user')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birth.father')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birth.mother')),
            ],
        ),
    ]
