# Generated by Django 4.0 on 2021-12-28 15:40

import birth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='nni',
            field=models.CharField(default=birth.utils.create_new_ref_number, editable=False, max_length=10, unique='True', verbose_name='nni'),
        ),
        migrations.AlterField(
            model_name='father',
            name='nni',
            field=models.CharField(default=birth.utils.create_new_ref_number, editable=False, max_length=10, unique='True', verbose_name='nni'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='nni',
            field=models.CharField(default=birth.utils.create_new_ref_number, editable=False, max_length=10, unique='True', verbose_name='nni'),
        ),
    ]
